[pytest]
asyncio_default_fixture_loop_scope = session
asyncio_mode = auto
filterwarnings =
    ignore::sqlalchemy.exc.MovedIn20Warning
    ignore::sqlalchemy.exc.SAWarning
    ignore::DeprecationWarning:datetime.*
    ignore::pytest.PytestDeprecationWarning:pytest_asyncio.*
